version: '3.8'
# docker system prune -a --volumes
services:

  web:
    image: library/nginx:1.25.2-alpine
    container_name: setup_web
    restart: always
    ports:
      - 8001:80
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      dockerfile: ./docker/php/Dockerfile
      target: "${BUILD_TARGET:-app}"
    container_name: setup_php
    restart: always
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      MYSQL_HOST: setup_db
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDIS_HOST: setup_cache
      REDIS_PORT: ${REDIS_PORT}

  db:
    image: mysql:8.0
    container_name: setup_db
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  cache:
    image: redis:latest
    container_name: setup_cache

volumes:
  mysqldata: