version: '3.8'
# docker system prune -a --volumes
services:

  web:
    build:
      dockerfile: ./docker/nginx/Dockerfile
    container_name: setup_web
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      dockerfile: ./docker/php/Dockerfile
    container_name: setup_php
    restart: always
    working_dir: /var/www

  db:
    image: mysql:8.1.0
    container_name: setup_db
    volumes:
      - mysqldata:/var/lib/mysql
    restart: unless-stopped # TODO set to "always"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: docker-setup

volumes:
  mysqldata: