version: '3.8'
# docker system prune -a --volumes
services:

  web:
    build:
        dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf

  app:
    build:
      dockerfile: ./docker/php/Dockerfile
      target: "${BUILD_TARGET:-app}"
    working_dir: /var/www
    volumes:
      - ./app:/var/www
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"

  db:
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  mysqldata: