name: TranslateThis
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Composer Dependencies
        working-directory: ./app
        run: composer install --prefer-dist
      - name: Run Tests
        working-directory: ./app
        run: composer run-phpunit tests
      - run: docker build --target app -t kmtsvetanov/php-composer:1.2 -f ./docker/php/Dockerfile .
      - run: docker build -t kmtsvetanov/nginx-php:1.0 -f ./docker/nginx/Dockerfile .
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push kmtsvetanov/php-composer:1.2
      - run: docker push kmtsvetanov/nginx-php:1.0